import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

export const FAQSection = () => {
  const categories = [
    {
      id: 'general',
      title: 'General & Capability',
      faqs: [
        {
          q: 'What exactly is TOBE and how does it work?',
          a: 'TOBE is the world's first Generative Commerce platform by WNE3. It lets you create, customize, and order apparel or merchandise just by typing what you imagine — like "a pastel hoodie with mountain art." Our AI instantly designs it, you preview it, and we make it only after you buy.'
        },
        {
          q: 'Can I really create anything, or are there design limits?',
          a: 'Almost anything — from minimal text to full-blown art, memes, or patterns. TOBE's AI interprets natural language, so even vague prompts like "a hoodie that feels calm and minimal" become real, tangible designs.'
        },
        {
          q: 'Do I need design experience to use TOBE?',
          a: 'Not at all. The platform is built for everyone — creators, students, and brands alike. Just describe what you want. No templates. No tools.'
        },
        {
          q: 'Can I use TOBE for products beyond apparel?',
          a: 'Yes. While phase one focuses on apparel and accessories, upcoming updates will include home décor, stationery, gifts, and digital collectibles — all generated by your imagination.'
        },
        {
          q: 'Does TOBE also generate mockups and previews?',
          a: 'Yes, every design appears instantly on realistic mockups like hoodies, mugs, or phone cases so you can visualize before buying.'
        },
        {
          q: 'Do you offer a managed or creator-assist service?',
          a: 'Absolutely. For brands or creators who prefer a hands-off approach, the platform automatically creates and manages a personalized sub-store for you — handling everything from design to order fulfillment.'
        },
        {
          q: 'What about sustainability—how is TOBE better than traditional retail?',
          a: 'Every purchase on TOBE contributes to a cleaner planet. Unlike traditional retail, which wastes millions of tons of apparel yearly, TOBE manufactures only what's needed — zero overstock, zero waste. Every order you make actively reduces carbon emissions and supports conscious, low-impact production.'
        },
        {
          q: 'Which region is TOBE available in, and when will it go global?',
          a: 'Our first launch focuses on India's urban markets. Global expansion will follow through international print-on-demand partners and ONDC's vendor network.'
        }
      ]
    },
    {
      id: 'customization',
      title: 'Customization & Control',
      faqs: [
        {
          q: 'How much control do I have over the final product design?',
          a: 'Full control — tweak colors, placement, and text until it feels right. TOBE's AI learns your preferences to refine every design over time.'
        },
        {
          q: 'Can I specify design styles or themes?',
          a: 'Yes — from "streetwear" and "minimalist" to "retro" or "eco aesthetic," TOBE adapts to your vibe and aesthetic instantly.'
        },
        {
          q: 'Can I generate collections or product lines under my brand?',
          a: 'Definitely. You can maintain a cohesive brand identity, reuse prompts, and build entire lines within your sub-store.'
        },
        {
          q: 'Can I personalize gifts or event merchandise?',
          a: 'Yes — just describe it: "gift hoodie for my best friend with our college name and inside joke." TOBE takes care of the rest.'
        },
        {
          q: 'Can small creators build their own stores?',
          a: 'Yes. Creators can open sub-stores inside TOBE, sell globally, and earn revenue. Unlike Amazon or Flipkart that charge up to 25% commission, TOBE's commission stays under 2%, ensuring creators keep more of what they earn.'
        },
        {
          q: 'Can I collaborate with other designers or creators?',
          a: 'Yes — co-create collections, share prompts, and launch collaborative drops seamlessly within the ecosystem.'
        },
        {
          q: 'Is the search really done with natural language?',
          a: 'Absolutely. Unlike traditional marketplaces that rely on keyword searches, TOBE understands nuance. Our AI interprets intent — for example, "a minimalist eco hoodie for urban cyclists" — and instantly generates the product that fits you perfectly.'
        }
      ]
    },
    {
      id: 'process',
      title: 'Process & Workflow',
      faqs: [
        {
          q: 'What's the step-by-step process for creating and ordering?',
          a: 'Describe your idea → AI generates options → refine and preview → order → product is made on demand → shipped to your door.'
        },
        {
          q: 'How long does it take from creation to delivery?',
          a: 'Each item is made post-purchase. Domestic deliveries typically take 3–5 days.'
        },
        {
          q: 'Can I upload my own artwork or mix it with AI designs?',
          a: 'Yes, TOBE supports hybrid design workflows — blend your uploads with AI creations effortlessly.'
        },
        {
          q: 'How accurate are final prints compared to previews?',
          a: 'With advanced color calibration, we ensure <5% variation between digital previews and printed output.'
        },
        {
          q: 'Can I brand packaging or add my logo?',
          a: 'Yes, premium and creator-tier users can include custom labels, tags, and inserts for a fully branded experience.'
        }
      ]
    },
    {
      id: 'pricing',
      title: 'Pricing & Plans',
      faqs: [
        {
          q: 'How does TOBE's pricing work?',
          a: 'There are no design fees — you pay only for what you order. Prices vary based on the product type and level of customization.'
        },
        {
          q: 'Do you charge commissions or platform fees?',
          a: 'Only under 2% per sale for creators — compared to 20–25% on major marketplaces.'
        },
        {
          q: 'Is there a subscription model for creators or brands?',
          a: 'Yes. Optional creator plans include advanced analytics, bulk credits, branded storefronts, and early access to new AI tools.'
        },
        {
          q: 'Can I try TOBE for free?',
          a: 'Yes — every new user gets free credits to explore AI product generation.'
        },
        {
          q: 'Are there discounts for bulk or corporate orders?',
          a: 'Yes — we support large orders, event merchandise, and company drops with customized fulfillment pricing.'
        }
      ]
    },
    {
      id: 'technical',
      title: 'Technical & Comparison',
      faqs: [
        {
          q: 'How is TOBE different from marketplaces like Amazon or Flipkart?',
          a: 'Traditional platforms show you static catalogs. TOBE generates unique products instantly from natural language — transforming imagination into inventory in seconds.'
        },
        {
          q: 'How does TOBE's sustainability compare to fast fashion?',
          a: 'TOBE's on-demand model cuts textile waste by up to 40% compared to traditional production, preventing overstock and reducing carbon emissions.'
        },
        {
          q: 'Do I need design or AI skills to use TOBE?',
          a: 'Not at all — if you can describe it, you can create it.'
        },
        {
          q: 'Can businesses integrate TOBE into their workflow?',
          a: 'Yes — upcoming APIs and B2B dashboards will enable direct integration for automated custom merch generation.'
        },
        {
          q: 'What resolution and format are visuals provided in?',
          a: 'All visuals are delivered in 300 DPI, print-ready formats suitable for production, marketing, and digital previews.'
        }
      ]
    }
  ];

  return (
    <section id="faq" className="relative py-16 px-4 space-gradient-light overflow-hidden">
      <div className="absolute inset-0 animated-gradient-bg opacity-50" />
      <div className="absolute inset-0 space-particles" />
      <div className="relative z-10 max-w-6xl mx-auto">
        <h2 className="text-center text-4xl md:text-5xl font-poppins font-bold gradient-text-animated mb-12">
          Frequently Asked Questions
        </h2>
        
        <Tabs defaultValue="general" className="w-full">
          <TabsList className="w-full h-auto p-1 bg-transparent border-b border-border/50 rounded-none flex flex-wrap justify-start gap-2 mb-8">
            {categories.map((category) => (
              <TabsTrigger
                key={category.id}
                value={category.id}
                className="data-[state=active]:bg-transparent data-[state=active]:text-primary data-[state=active]:border-b-2 data-[state=active]:border-primary data-[state=active]:shadow-none rounded-none px-4 py-3 text-sm md:text-base font-medium text-muted-foreground hover:text-foreground transition-all border-b-2 border-transparent"
              >
                {category.title}
              </TabsTrigger>
            ))}
          </TabsList>

          {categories.map((category) => (
            <TabsContent key={category.id} value={category.id} className="mt-0">
              <div className="rounded-3xl border border-border/50 card-gradient p-4 md:p-6">
                <Accordion type="single" collapsible className="w-full divide-y divide-border/50">
                  {category.faqs.map((faq, idx) => (
                    <AccordionItem key={idx} value={`${category.id}-${idx}`} className="border-none">
                      <AccordionTrigger className="text-left px-2 md:px-4 py-4 text-foreground hover:no-underline">
                        <span className="font-medium text-base md:text-lg">{faq.q}</span>
                      </AccordionTrigger>
                      <AccordionContent className="px-2 md:px-4 text-muted-foreground text-sm md:text-base leading-relaxed">
                        {faq.a}
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </div>
            </TabsContent>
          ))}
        </Tabs>
      </div>
    </section>
  );
};

export default FAQSection;
